In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5]

In [6]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
np.array(x)

array([1, 2, 3, 4, 5])

In [7]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.zeros((3))

array([0., 0., 0.])

In [11]:
np.zeros((3,3)) + 6

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [12]:
np.ones(1)

array([1.])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.arange(3)

array([0, 1, 2])

In [24]:
np.arange(30).reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])